### PR TITLE
Merge changes from Prism Launcher 9.1

### PR DESCRIPTION
**Pull request by evan-goode**
Prism Launcher 9.0 made substantial changes to the authentication logic (https://github.com/PrismLauncher/PrismLauncher/pull/2402), so this merge involved a lot of refactoring and rewriting the authlib-injector authentication code to match Prism Launcher's new structure. But the error handling while adding a new authlib-injector account is now much nicer (no more "Mojang user authentication ended in a network error").

I'd really appreciate volunteers to test this before it's released!

Suggested things to test:

- Microsoft accounts
  + Log in
  + Refresh
  + Restart launcher
  + Launch game
  + Join server
  + Manage skins
- Authlib-injector accounts
  + Log in
  + Refresh
  + Restart launcher
  + Launch game
  + Join server
  + Manage skins (this is ONLY expected to work for Drasl accounts, other authlib-injector servers are not supported yet, see https://github.com/unmojang/FjordLauncher/issues/37)
- FTB Import
- [Prism Launcher's new Java downloader](https://github.com/PrismLauncher/PrismLauncher/pull/2069)
- macOS
- Linux
- Windows
- Anything you can think of

### CODE REVIEW

**Comment by LunisCandle** [comment]
Modrinth and FTB App Import both seem to have this extra unusable search bar at the bottom(?) 
image
This is not the case in upstream Prism 9.1

**Comment by LunisCandle** [comment]
The add mojang button from the current version of fjord is also missing, is this intentional?

**Comment by catfromplan9** [comment]
> The add mojang button from the current version of fjord is also missing, is this intentional?

Mojang accounts do not exist anymore, so yes

**Comment by catfromplan9** [comment]
> Modrinth and FTB App Import both seem to have this extra unusable search bar at the bottom(?) image This is not the case in upstream Prism 9.1

Could you show an image of how it looks in upstream prism?

**Comment by LunisCandle** [comment]
> > The add mojang button from the current version of fjord is also missing, is this intentional?
> 
> Mojang accounts do not exist anymore, so yes

Yet the previous version of Fjord still has the option there, and microsoft accounts haven't existed for over a year.

**Comment by LunisCandle** [comment]
> > Modrinth and FTB App Import both seem to have this extra unusable search bar at the bottom(?) image This is not the case in upstream Prism 9.1
> 
> Could you show an image of how it looks in upstream prism?
image

image

**Comment by evan-goode** [comment]
Removing the Mojang account button was intentional, no reason to keep it around any longer. I might as well go ahead and rip out more of the Mojang account logic while I'm at it, like Prism already has.

I'll look into that search bar.

**Comment by evan-goode** [comment]
Not sure where those search bars came from :)

I think everything is good to go, I will merge soon unless something else is found.

**Comment by LunisCandle** [comment]
Presuming the removal of the PollyMC contributors credit in the about section was intentional, I haven't come across any issues since!

**Comment by evan-goode** [comment]
>Presuming the removal of the PollyMC contributors credit in the about section was intentional, I haven't come across any issues since!

Yeah, that was a (old) change from upstream.

**Comment by LunisCandle** [comment]
Polly with two Ls, not the one under Lenny but understood!

**Comment by evan-goode** [comment]
Oh whoops, no that was a mistake, I'll add that back.

**Comment by catfromplan9** [comment]
> > Presuming the removal of the PollyMC contributors credit in the about section was intentional, I haven't come across any issues since!
> 
> Yeah, that was a (old) change from upstream.

I think this should be reverted

**Comment by evan-goode** [comment]
It was reverted.

**Pull request merged**
